### ISSUE TITLE
README Air quality classification should be in ppb, not ppm

### ISSUE THREAD

**Issue by SamDev-7** [RobTillaart/AGS02MA#26]
As per the [source stated](https://learn.kaiterra.com/en/resources/understanding-tvoc-volatile-organic-compounds) in the README, the safe TVOC levels shown are stated in ppb.

<img src="https://learn.kaiterra.com/hs-fs/hubfs/Email%20Series/IAQ%20Series/AQI%20tvoc.png?width=2898&name=AQI%20tvoc.png" alt="AQI tvoc" width="50%">

 The README shows the same numbers with the units being ppm, which is incorrect.
<img src="https://github.com/RobTillaart/AGS02MA/assets/66446458/c9c09b26-725b-480d-955f-050d7271fcd0" alt="Screenshot of chart in README" width="35%">

**Comment by RobTillaart** [comment]
Thanks for pointing out this bug in the document ation.
Will work on it right away
